### ISSUE TITLE
Update to 1.21.1

### ISSUE THREAD

**Issue by ArduFish** [KosmX/minecraftPlayerAnimator#102]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. This mod is not updated to 1.21.1.

**Describe the solution you'd like**
Update this mod to 1.21.1.

**Describe alternatives you've considered**

**Additional context**

**Comment by mpustovoi** [comment]
Now when Better Combat has been updated to 1.21.1, it's weird to see that its required dependency isn't available on this version.

**Comment by ArduFish** [comment]
@mpustovoi 1.21 mods work on 1.21.1

**Comment by Fyoncle** [comment]
> @mpustovoi 1.21 mods work on 1.21.1

Then mark it as compatible?

**Comment by ArduFish** [comment]
@KosmX yeah, it should be marked as compatible.
