### ISSUE TITLE
[API] Easings don't work on GeckoLib animations.

### ISSUE THREAD

**Issue by ZigyTheBird** [KosmX/minecraftPlayerAnimator#112]
**Describe the bug**
The mod successfully reads the easings it's supposed to use on each keyframe and stores it in the appropiate KeyFrame class instances but for some reason in-game linear ease is always used instead of the intended easing.
This problem seems to not occur with Blender animations.
Here is a discord post with the original person that found this bug: https://discord.com/channels/737216980095991838/1285522357573914664
OP may have also found a bug related to bending: https://discord.com/channels/737216980095991838/1285522357573914664/1285600739787276348

**To Reproduce**
1. Play a GeckoLib animation with easings
2. See linear easing being used regardless of the intended easing

**Setup config (minecraft, modloader, libraries):**
I tested this on a fork of the 1.21 branch of this very mod but it seems to occur on 1.20.1 as well even without any other libraries or mods involved.
Things broke way less on my 1.21 branch than in OP's 1.20.1 dev environment though.

**Comment by dima-dencep** [comment]
It works, but in a different way

**Comment by ZigyTheBird** [comment]
@dima-dencep what do you mean by that?

**Comment by dima-dencep** [comment]
Easings work, but they look different in game than they do in blockbench, etc

**Comment by ZigyTheBird** [comment]
TBH I am not really good at telling easings apart :p
I showed a clip of me playing some GeckoLib animations to a guy in the afformentioned discord post and he said that the easings were linear
Either way this is a problem that's worth addressing

**Comment by dima-dencep** [comment]
Well, if easings didn't work, your animation would be 20 frames/second

**Comment by ZigyTheBird** [comment]
Fixed by #96 probably?
