### ISSUE TITLE
1.20.1 Performance Optimization

### ISSUE THREAD

**Issue by dfdffish** [KosmX/minecraftPlayerAnimator#132]
**Is your feature request related to a problem? Please describe.**
When animations starting to play, it causes a noticeable FPS drop, for example like 150 to 90. 
This become significant when having shaderpacks on, which FPS drop is like 100 to 40.

**Describe the solution you'd like**
I think this version of the mod really needs some optimizations. Do higher versions have better performance?

**Comment by ZigyTheBird** [comment]
I have never encountered any noticable performance issues while playing player animations.
There isn't enough info for me to help you here.
Share as much info as you possibly can like all the mods you have installed and their versions. 
If you are a developer share your project's GitHub repository so I can see how you are playing the animation

**Comment by dima-dencep** [comment]
Spark profiler maybe?
https://spark.lucko.me/

**Comment by dfdffish** [comment]
**Game Version**:1.20.1 Forge 47.3.22
**PlayerAnimator**: player-animation-lib-forge-1.0.2-rc1+1.20
**Mod that utilizes PlayerAnimator**: SlashBladeResharped-1.20.1-1.1.11 
https://www.curseforge.com/minecraft/mc-mods/slashblade-resharped
**Other possibly related mods**: 
Skin Layers 3D: skinlayers3d-forge-1.7.4-mc1.20.1
Not Enough Animations: notenoughanimations-forge-1.9.0-mc1.20.1
First-person Model: firstperson-forge-2.4.8-mc1.20.1
Oculus: oculus-mc1.20.1-1.8.0
Embeddium: embeddium-0.3.31+mc1.20.1

Basically as long as I can see the animation playing, I get a FPS drop.
The performance issue only occurs when swinging SlashBlades with Third-Person or using First-person Model to render body. 
I haven't test it in multiplayer though.

**Before**
![image](https://github.com/user-attachments/assets/99127349-2939-46d5-b1e3-7a049a1bb571)
**Using**
![image](https://github.com/user-attachments/assets/4594100c-37ea-467d-8a31-78d7105f9986)

Also, If PlayerAnimator is not installed, Swinging SlashBlades will no longer cause FPS drop. 
Is this normal or I'm just too sensitive? Let me know if there is any problem.

**Comment by dfdffish** [comment]
> Spark profiler maybe? https://spark.lucko.me/

I think 1.20.1 is not supported? Cant find it anywhere.

**Comment by dima-dencep** [comment]
https://www.curseforge.com/minecraft/mc-mods/spark/files/all?version=1.20.1&showAlphaFiles=show

**Comment by ZigyTheBird** [comment]
Dropping 60 frames for something as simple as animating the player isn't normal, no.
