### ISSUE TITLE
 Could not get unknown property 'player_anim' for root project 'forge' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by Yaumama** [KosmX/minecraftPlayerAnimator#37]
I am getting this error:
` Could not get unknown property 'player_anim' for root project 'forge' of type org.gradle.api.Project.`
While running the RunClient task.

**Comment by KosmX** [comment]
Please specify!
 - Are you trying to run the library, or a project using the library?
 - Are you using Forge gradle or architectury loom?
 - buildscript?

**Comment by Yaumama** [comment]
Sorry for not specifying, I am using minecraft 1.19.2 forge 43.1.7 with forge gradle and am trying to run a project using the library.

**Comment by KosmX** [comment]
oh, I think i know what is your problem.
`${project.player_anim}` is a reference to `gradle.properties` field.

Add `player_anim = 0.4.0` to gradle.properties.

**Comment by Yaumama** [comment]
Thanks! It worked!
