### ISSUE TITLE
[1.18.2-0.4.0] - Mixin: Critical injection failure

### ISSUE THREAD

**Issue by MattB70** [KosmX/minecraftPlayerAnimator#38]
**Describe the bug**
Gradle runs refresh successfully, though the game fails to launch due to a Mixin error similar to what happens when the Mixin refMap lines are missing from the build.gradle. I expect this to be the result of a silly mistake as this version of Player Animator has worked fine in other environments.

**Buildscript content or link to content (If you don't share your code, I cannot debug it):**
https://github.com/MattB70/Cups-Arsenal/blob/1.18.2/build.gradle
https://github.com/MattB70/Cups-Arsenal/blob/1.18.2/gradle.properties

**To Reproduce**
1. Run `gradle runClient`
2. See error

**Expected behavior**
The game should not crash. I changed a variable name from `player_anim` to `playeranim_version` to match my typical convention, but it should (and doesn't seem to) have any effect on the outcome, otherwise I can't see anything wrong with the environment setup.

**Environment (please complete the following information):**
 - OS: Windows 11, amd64
 - IDE IntelliJ
 - Gradle 7.5.1
 - JDK version 17.0.5+8 Eclipse Adoptium
 - gradle plugin ForgeGradle
 - Minecraft, Loader: 1.18.2, Forge 40.1.84

**Additional context**
I upgraded my Gradle from 7.4.0 to 7.5.1 to match your environment on the off chance it was interpreting the runs differently, but it didn't help.
Here are some logs so you can take a stab at investigating without needing to pull my repo, though feel free to do what you need:
gradle build (unremarkable): https://gist.github.com/MattB70/0e21aaf48fd01877008121ba0a8a35a8
game crash (clear mixin error):  https://gist.github.com/MattB70/d8ce130e97ac5f87bae81cf55cb5d4f5

Thanks :)

**Comment by KosmX** [comment]
Player animator `0.4.0` is for Minecraft 1.19(.1/2)  
For MC 1.18.2 use `0.4.0+1.18`

**Comment by MattB70** [comment]
I just caught that right now, but it didn't change the error. Now I'm really blown away. 0.4.0+1.18 is the version I use in my modpack, and that matches the rest of this environment pretty much exactly. I'll push this change and send over some new logs.

Updated gradle:
https://github.com/MattB70/Cups-Arsenal/blob/1.18.2/build.gradle
https://github.com/MattB70/Cups-Arsenal/blob/1.18.2/gradle.properties

So, now on 0.4.0+1.18 as it should be, I get these results:
gradle build (unremarkable): https://gist.github.com/MattB70/cb2151ce9246e434e599c5aca184320b
game crash (clear mixin error): https://gist.github.com/MattB70/be6932c845ecc488373c6b73bd41f061

Sorry for the messy issue with the wrong version present, I had been switching through versions to find which worked and landed on the wrong one for the report. This is now the updated issue report.

**Comment by KosmX** [comment]
Remap property is probably missing...  
Are you using IntelliJ run or `runClient` command? Those are different.

If you use IntelliJ run, please rerun `getIntellijRuns` task to fix the missing property.  
> You may close the issue if it works.

**Comment by MattB70** [comment]
Yep, I knew it was something silly I missed.
That did it, thanks for the help!
