### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by OffsetMonkey538** [KosmX/minecraftPlayerAnimator#4]
Is there an example mod I could use to learn how to use this? Planning to use this for my modfest entry

**Comment by KosmX** [comment]
uh- well,  
In this project, there is a [testmod](https://github.com/KosmX/fabricPlayerAnimation/tree/dev/minecraft/fabric/src/testmod)   

The project is implemented in [emotecraft](https://github.com/KosmX/emotes) and [Better Combat](https://github.com/ZsoltMolnarrr/BetterCombat)  

BetterCombat implementation is much simpler... (emotecraft is a huge multi-module project, hard to understand that.)  

Originally I started the animation library for Emotecraft, you might find how-to animate guides/tools there:
https://github.com/KosmX/emotes/wiki/Animation-in-Minecraft  
[Blender and BlockBench models for ~~emotecraft~~ animation library](https://github.com/KosmX/emotes/tree/dev/blender)  


If you want, you can contact me on Discord: `KosmX#7620`

**Comment by KosmX** [comment]
There are some example mods for Fabric and Forge. See updated README for links!  
https://github.com/KosmX/minecraftPlayerAnimator#example-mods
