### ISSUE TITLE
Minecraft log spam bug

### ISSUE THREAD

**Issue by maxplayz109X** [KosmX/minecraftPlayerAnimator#45]
**Describe the bug**
when I open Minecraft it will keep spam loading screens 

**To Reproduce**
1. Go to minecraft
2. Click on play on fabric loader 1.19.3
3. Minecraft is loading 
4. and loading screens start to spam

**Screenshots**
https://youtu.be/Wz6wANe_pbo
Minecraft 1.19.3
...
```

**Comment by KosmX** [comment]
Can't reproduce.

Please open a new issue, and fill the requested fields including mod versions and game logs!   
If you don't know where to find logs, here is a help:  
https://emotes.kosmx.dev/guide/logs
