### ISSUE TITLE
Crash with optifine 

### ISSUE THREAD

**Issue by JonathanDI7** [KosmX/minecraftPlayerAnimator#47]
When you load player-animator with OptiFine_1.18.2_HD_U_H7.jar the game will crash when you load a world, by itself or with better combat and cloth config. 
Forge 40.2.0
[crash-2023-02-11_20.48.00-server.txt](https://github.com/KosmX/minecraftPlayerAnimator/files/10714757/crash-2023-02-11_20.48.00-server.txt)

**Comment by KosmX** [comment]
I think this is caused by optifine itself (try to replicate with only OF).  
If you still believe this is caused by PlayerAnimator, please share full client logs!

**Comment by JonathanDI7** [comment]
I found out the issue, it was because I didn't have the right version of optifine. It would load by itself fine, but when paired with player-animator it would crash.  Thank you for the fast response!
preview_OptiFine_1.18.2_HD_U_H9_pre2.jar
