### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ChromaPIE** [KosmX/minecraftPlayerAnimator#53]
**Describe the bug**
Title. The mod version is fabric-1.0.0-rc1.
The crash report made me suspect Supplementaries at first. But the game actually launched to the main menu when I rolled PlayedAnimator back to 0.4.2.

**Crash report (please copy the whole crash report!)**
https://mclo.gs/6bBrjgV

**Comment by KosmX** [comment]
With 1.0.0 first person api was moved from bettercombat to playeranimator

Please use 0.4.2 for now (or better comban >=1.6)
