### ISSUE TITLE
[1.18.2] Crash when Spectating Modded Entities

### ISSUE THREAD

**Issue by Camawama** [KosmX/minecraftPlayerAnimator#57]
**Describe the bug**
Anytime I try to spectate a modded entity, my client crashes

**To Reproduce**
1. Playing my CamaCraft modpack
2. Enter spectator mode
3. spectate any non-vanilla entity

**Crash report (please copy the whole crash report!)**
[crash-2023-03-01_12.11.03-client.txt](https://github.com/KosmX/minecraftPlayerAnimator/files/10864153/crash-2023-03-01_12.11.03-client.txt)

**Logs (if you have logs from that run, please share it):**
[latest.log](https://github.com/KosmX/minecraftPlayerAnimator/files/10864145/latest.log)

**Comment by KosmX** [comment]
Sorry,  

should be fixed with version 1.0.1

**Comment by Camawama** [comment]
It's fixed, thank you!
