### ISSUE TITLE
1.18.2 rendering overlay crash

### ISSUE THREAD

**Issue by EightBlade** [KosmX/minecraftPlayerAnimator#65]
When I play the game with this + better combat installed in my custom modpack there's a 80% chance or such of the game crashing. Here's the latest crash log below.

https://pastebin.com/vg9qqB2E

Minecraft 1.18.2

**Comment by KosmX** [comment]
It does not contain *any* relevant information for this library.   
It might caused by `Corail Tombstone`.  

If you're still sure playeranimator is responsible for the crash, please contact me somewhere ([kosmx.dev](https://kosmx.dev/))

**Comment by EightBlade** [comment]
It seems like a mod conflict, as disabling this allows it to run with Corail and vice versa. Never the less I'll make a post on the relevant hub.
