### ISSUE TITLE
Deleted by issue author.

### ISSUE THREAD

**Issue by ProsperCraft** [KosmX/minecraftPlayerAnimator#68]
Deleted by issue author.

**Comment by KosmX** [comment]
This is an issue with Iron spells and spellbooks mod, not playeranimator.  
> PlayerAnimator may be required on server-side, but it is not throwing the error message.  

Issue:
https://github.com/iron431/Irons-Spells-n-Spellbooks/blob/c392d5fe5f31e823ad56ad455509f325429fcc8b/src/main/resources/mixins.irons_spellbooks.json#L8

This mixin config does not respect sideness.
