### ISSUE TITLE
Crashing with rubidium+oculus

### ISSUE THREAD

**Issue by TheKuwagata** [KosmX/minecraftPlayerAnimator#71]
Minecraft 1.20.1

[crash-2023-10-18_03.14.53-client.txt](https://github.com/KosmX/minecraftPlayerAnimator/files/12951958/crash-2023-10-18_03.14.53-client.txt)

**Comment by KosmX** [comment]
It appears to be an invalid rubidium or oculus version, if not, please send game logs (not just crash report)

**Comment by TheKuwagata** [comment]
[2023-10-18-7.log](https://github.com/KosmX/minecraftPlayerAnimator/files/12954722/2023-10-18-7.log)
[latest.log](https://github.com/KosmX/minecraftPlayerAnimator/files/12954733/latest.log)
Is it logs? this with latest versions embeddium+oculus


[2023-10-18-7.log](https://github.com/KosmX/minecraftPlayerAnimator/files/12955719/2023-10-18-7.log)
[latest.log](https://github.com/KosmX/minecraftPlayerAnimator/files/12955723/latest.log)
this with older versions rubidium+oculus

**Comment by KosmX** [comment]
It appears to be a Forge/Rubidium issue.  
Please try to run the game with the latest rubidium (0.7.1 when I write this)  
Or just use Fabric

**Comment by ghost** [comment]
@coppalka @KosmX 
To Fix this read the comments in this issue in https://github.com/Asek3/Oculus/issues/395

"Hopefully this save someone some future headache, If you encounter this error.

1. Disable Oculus and Rubidium then launch the game.
2. You should then be presented with some missing dependencies install them.
3. Add Oculus and Rubidium back and things should work.
For some reason Oculus and Rubidium prevents the missing dependencies GUI from opening, not sure why and I'm to lazy to figure it out."
