### ISSUE TITLE
Add 1.20.x compatibility

### ISSUE THREAD

**Issue by 0xSnowflakeXD** [KosmX/minecraftPlayerAnimator#81]
**Is your feature request related to a problem? Please describe.**
Nope. However, it's hard to use mods require this mod and Minecraft 1.20.2 (E.g. Better Combat)

**Describe the solution you'd like**
Add backport for 1.20.2, or add compatibility for all 1.20 versions

**Describe alternatives you've considered**
No?

**Additional context**
No.

**Comment by KosmX** [comment]
1.20.4 versions should work on 1.20.2

**Comment by 0xSnowflakeXD** [comment]
Thanks. I'm closing this issue on my own.
