### ISSUE TITLE
[API] Skintight geckolib armor doesn't render right during animations

### ISSUE THREAD

**Issue by thomasglasser** [KosmX/minecraftPlayerAnimator#82]
**Describe the bug**
When animating the player with a custom skintight geckolib armor model, the armor is rendered in the wrong place.

**To Reproduce**
1. Make a skintight geckolib armor model
2. Make a player animation
3. Perform animation in-game

**Expected behavior**
The model stays skintight

**Screenshots**
Vanilla iron armor:
![2024-02-27_20 28 16](https://github.com/KosmX/minecraftPlayerAnimator/assets/63979449/8e3a9554-8d5f-4af3-940d-f2c56a569c76)
![2024-02-27_20 28 54](https://github.com/KosmX/minecraftPlayerAnimator/assets/63979449/3aa0a4c0-95ca-4503-99f9-5270fb546570)

Custom armor:
![2024-02-27_20 28 07](https://github.com/KosmX/minecraftPlayerAnimator/assets/63979449/981786cc-bb05-4b9f-9a73-b29c59d106bc)
![2024-02-27_20 29 00](https://github.com/KosmX/minecraftPlayerAnimator/assets/63979449/ef659bb4-b8ec-47bf-8676-95d12a69c90d)

**Setup config (minecraft, modloader, libraries):**
 - Minecraft version: 1.20.4
 - Mod loader: All
 - PlayerAnimator Library version 1.0.2-rc1+1.20

**Other mods (If you use other mods, please specify! it might be an incompatibility):**
Geckolib

**Comment by thomasglasser** [comment]
[model.zip](https://github.com/KosmX/minecraftPlayerAnimator/files/14427988/model.zip)
Here's the model I use

**Comment by KosmX** [comment]
The pivot of your custom leggings is incorrect. Please match that to the vanilla model
![image](https://github.com/KosmX/minecraftPlayerAnimator/assets/15692868/73b35fe0-4593-44a1-8689-e510eebae895)

**Comment by thomasglasser** [comment]
Fixing the pivots of the groups and subgroups fixed it, thanks
