### ISSUE TITLE
Using mod crashes game with null

### ISSUE THREAD

**Issue by wolfieboy09** [KosmX/minecraftPlayerAnimator#85]
**Describe the bug**
I have `iron_spellbooks` installed, and it uses this mod. I uninstalled player animator, and the game loads.

**To Reproduce**
1. Install `iron_spellbooks`
2. play
3. game crashse

**Screenshots**

**Crash report (please copy the whole crash report!)**
```

```

**Comment by wolfieboy09** [comment]
![image](https://github.com/KosmX/minecraftPlayerAnimator/assets/105564186/deaba9c4-3755-4feb-9aad-527c6fe91570)

**Comment by KosmX** [comment]
Please share that crash report or I can't help.  

If you have the crash report, please reopen this issue.
