### ISSUE TITLE
Add Chinese language?

### ISSUE THREAD

**Issue by QianMuu** [KosmX/minecraftPlayerAnimator#89]
I briefly translated the Chinese language myself. if it is possible. You can add it. This mod is very good.
(However, I cannot Chineseize the creature name and status. I hope you can improve it in the future.)
[
[zh_cn.json](https://github.com/KosmX/minecraftPlayerAnimator/files/15442007/zh_cn.json)

![{3AE8952B-936F-427f-8099-7BFF24DD0DD1}](https://github.com/KosmX/minecraftPlayerAnimator/assets/50398180/3853dc8c-1684-4c42-a004-dee90804fd71)

**Comment by KosmX** [comment]
It is a different mod, not related to playerAnimator.
