### ISSUE TITLE
Update to 1.21

### ISSUE THREAD

**Issue by pavelbat3** [KosmX/minecraftPlayerAnimator#92]

**Comment by idkmandev** [comment]
i second this

**Comment by SfortzaPhantom** [comment]
Emotecraft has a good code so you can port it by yourself. It won't help if you'll keep constantly spamming with "update to _insert_my_shitty_version_of_minecraft_made_by_majong_".

**Comment by KosmX** [comment]
https://github.com/KosmX/minecraftPlayerAnimator/tree/1.21
